server:
  port : 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter-like
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ruzgaremirofficial@gmail.com
    password: tokm ipcp kyzy jjow
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
